name: Demo
on:
  push: {}
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn
      - name: demo
        run: |
          ./cli.js create-deployment \
            --owner=dtinth --repo=github-deployments-cli --ref=$GITHUB_SHA \
            --environment=demo --production-environment \
            --required-contexts= \
            | tee /tmp/deployment.json

          ./cli.js create-deployment-status \
            --owner=dtinth --repo=github-deployments-cli --deployment=/tmp/deployment.json \
            --state=in_progress \
            --log-url=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID

          ./cli.js create-deployment-status \
            --owner=dtinth --repo=github-deployments-cli --deployment=/tmp/deployment.json \
            --state=success \
            --log-url=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID \
            --target-url=https://github.com/dtinth/github-deployments-cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
